#!/usr/bin/env python3
"""Build HWPX tables from golden templates generated by python-hwpx.

Raw XML table construction often crashes H2Orestart (LibreOffice HWPX plugin)
because many undocumented attributes are required. This module generates tables
via python-hwpx API at runtime, producing H2Orestart-compatible XML.

Usage as library:
    from table_builder import build_table_xml
    xml_str = build_table_xml([
        ["연도", "시장 규모", "성장률"],
        ["2024", "4,200", "15%"],
        ["2025", "5,100", "21%"],
    ])

Usage as CLI:
    python table_builder.py 3 4 -o table.xml                    # empty 3x4
    python table_builder.py --csv data.csv -o table.xml          # from CSV
    python table_builder.py --json '[["a","b"],["c","d"]]' -o table.xml
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
import tempfile
import zipfile
from pathlib import Path

from lxml import etree


def build_table_xml(
    data: list[list[str]],
    col_widths: list[int] | None = None,
) -> str:
    """Build a table XML fragment via python-hwpx API.

    Args:
        data: 2D list of cell text. First row is typically header.
        col_widths: Optional column widths in HWPUNIT. Auto-calculated if None.

    Returns:
        Pretty-printed XML string of the <hp:tbl> element.
    """
    from hwpx import HwpxDocument

    rows = len(data)
    cols = len(data[0]) if data else 0

    if rows == 0 or cols == 0:
        raise ValueError("Table must have at least 1 row and 1 column")

    doc = HwpxDocument.new()
    table = doc.add_table(rows=rows, cols=cols)
    for r, row in enumerate(data):
        for c, cell_text in enumerate(row):
            if c < cols:
                table.set_cell_text(r, c, cell_text)

    # Save to temp, extract table XML
    tmp = tempfile.mktemp(suffix=".hwpx")
    try:
        doc.save_to_path(tmp)
        with zipfile.ZipFile(tmp, "r") as zf:
            section = zf.read("Contents/section0.xml")
    finally:
        Path(tmp).unlink(missing_ok=True)

    ns = {"hp": "http://www.hancom.co.kr/hwpml/2011/paragraph"}
    root = etree.fromstring(section)
    tbl = root.find(".//hp:tbl", ns)

    if tbl is None:
        raise RuntimeError("python-hwpx did not produce a table element")

    etree.indent(tbl, space="  ")
    return etree.tostring(tbl, pretty_print=True, encoding="unicode")


def build_table_paragraph_xml(
    data: list[list[str]],
) -> str:
    """Build a complete <hp:p> element containing a table.

    Returns XML string ready to insert into section0.xml.
    """
    tbl_xml = build_table_xml(data)

    ns_hp = "http://www.hancom.co.kr/hwpml/2011/paragraph"
    p_xml = (
        f'<hp:p xmlns:hp="{ns_hp}" paraPrIDRef="0" styleIDRef="0">'
        f'<hp:run charPrIDRef="0">'
        f'{tbl_xml}'
        f'</hp:run>'
        f'</hp:p>'
    )
    # Parse and re-serialize for clean formatting
    p_el = etree.fromstring(p_xml)
    etree.indent(p_el, space="  ")
    return etree.tostring(p_el, pretty_print=True, encoding="unicode")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build HWPX table XML from data"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--csv", metavar="FILE", help="CSV file to read")
    group.add_argument("--json", metavar="JSON", help="JSON 2D array string")
    parser.add_argument("rows", nargs="?", type=int, help="Number of rows (if no data)")
    parser.add_argument("cols", nargs="?", type=int, help="Number of columns (if no data)")
    parser.add_argument("-o", "--output", help="Output XML file (default: stdout)")
    parser.add_argument("--paragraph", action="store_true",
                        help="Wrap table in <hp:p> element")
    args = parser.parse_args()

    data: list[list[str]] = []

    if args.csv:
        with open(args.csv, "r", encoding="utf-8") as f:
            data = list(csv.reader(f))
    elif args.json:
        data = json.loads(args.json)
    elif args.rows and args.cols:
        data = [["" for _ in range(args.cols)] for _ in range(args.rows)]
    else:
        parser.error("Provide --csv, --json, or rows+cols")

    if args.paragraph:
        xml = build_table_paragraph_xml(data)
    else:
        xml = build_table_xml(data)

    if args.output:
        Path(args.output).write_text(xml, encoding="utf-8")
        print(f"Table XML written to {args.output}", file=sys.stderr)
    else:
        print(xml)


if __name__ == "__main__":
    main()
